import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Container from '../components/layout/Container';
import Header from '../components/layout/Header';
import Hero from '../components/layout/Hero';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anne Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header />
        <Hero />
      </Container>
    </div>
  );
};

export default Home;
