import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/layout/Hero';
import PrimaryContent from '../components/PrimaryContent';
import { request } from '../services/request';
import { Article } from './articles/[slug]';
import qs from 'qs';

export interface Category {
  id: number;
  attributes: {
    name: string;
    slug: string;
    createdAt: string;
    updatedAt: string;
  };
}

interface Props {
  articles?: Article[];
  categories: Category[];
}

const Home = ({ articles, categories }: Props) => {
  return (
    <div>
      <Head>
        <title>Anne Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <PrimaryContent articles={articles} categories={categories} />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const query = qs.stringify(
      {
        populate: {
          author: {
            populate: ['picture'],
          },
          image: '*',
          category: '*',
        },
      },
      {
        encodeValuesOnly: true,
      }
    );
    const { data: articles } = await request.get(`/articles?${query}`);
    const { data: categories } = await request.get('/categories');
    return {
      props: {
        articles: articles.data,
        categories: categories.data,
      },
      revalidate: 10,
    };
  } catch (e) {
    console.log(e);
    return {
      props: {
        articles: null,
      },
    };
  }
};

export default Home;
